# Generated by Django 4.1.3 on 2025-03-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.TextField(db_column='Product_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('buying_price', models.IntegerField(db_column='Buying Price')),
                ('selling_price', models.IntegerField(db_column='Selling Price')),
                ('profit', models.IntegerField(db_column='Profit')),
                ('category', models.TextField(db_column='Category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
