# Generated by Django 4.1.3 on 2025-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='buying_price',
            field=models.DecimalField(db_column='Buying Price', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(db_column='Category', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(db_column='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(db_column='Product_ID', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='profit',
            field=models.DecimalField(db_column='Profit', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='selling_price',
            field=models.DecimalField(db_column='Selling Price', decimal_places=2, max_digits=10),
        ),
    ]
